-- 코드를 입력하세요
WITH SUB AS (
SELECT  
    B.AUTHOR_ID, 
    B.CATEGORY,
    SUM(B.PRICE * S.SALES) AS TOTAL_SALES
    
FROM BOOK AS B
INNER JOIN BOOK_SALES AS S
ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY B.AUTHOR_ID, B.CATEGORY
)



SELECT A.AUTHOR_ID, A.AUTHOR_NAME, S.CATEGORY, S.TOTAL_SALES
FROM SUB AS S
INNER JOIN AUTHOR AS A
ON S.AUTHOR_ID = A.AUTHOR_ID
ORDER BY A.AUTHOR_ID ASC, S.CATEGORY DESC
