-- 코드를 입력하세요
WITH SUB AS (
    SELECT ID, CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
)

SELECT A.CART_ID AS CART_ID
FROM CART_PRODUCTS AS A
INNER JOIN SUB AS B ON A.CART_ID = B.CART_ID
WHERE NAME = 'Yogurt'
ORDER BY CART_ID ASC

