-- 코드를 입력하세요
WITH BEST AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS BEST
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO AS A
INNER JOIN BEST AS B ON B.BEST = A.FAVORITES AND A.FOOD_TYPE = B.FOOD_TYPE
ORDER BY A.FOOD_TYPE DESC