-- 코드를 작성해주세요
SELECT ID,
    CASE 
        WHEN RANKING <= (TOTAL  * 0.25) THEN 'CRITICAL'
        WHEN RANKING <= (TOTAL  * 0.5) THEN 'HIGH'
        WHEN RANKING <= (TOTAL  * 0.75) THEN 'MEDIUM'
    ELSE 'LOW' END AS COLONY_NAME
FROM (
    SELECT ID, RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANKING, COUNT(*) OVER () AS TOTAL
    FROM ECOLI_DATA 
) AS SUB
ORDER BY ID
