WITH DISCOUNT_PLAN AS (
    SELECT 
        DURATION_TYPE, 
        REPLACE(DISCOUNT_RATE, '%', '') / 100 AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
)

SELECT 
    H.HISTORY_ID,
    CASE 
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 
            THEN (C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1)) * 
                 (1 - COALESCE((SELECT DISCOUNT_RATE FROM DISCOUNT_PLAN WHERE DURATION_TYPE = '90일 이상'), 0))
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 
            THEN (C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1)) * 
                 (1 - COALESCE((SELECT DISCOUNT_RATE FROM DISCOUNT_PLAN WHERE DURATION_TYPE = '30일 이상'), 0))
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 
            THEN (C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1)) * 
                 (1 - COALESCE((SELECT DISCOUNT_RATE FROM DISCOUNT_PLAN WHERE DURATION_TYPE = '7일 이상'), 0))
        ELSE C.DAILY_FEE * (DATEDIFF(H.END_DATE, H.START_DATE) + 1)
    END AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR C
JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
WHERE 
    C.CAR_TYPE = '트럭'
ORDER BY 
    FEE DESC, 
    H.HISTORY_ID DESC;
