-- 코드를 입력하세요
SET @HOUR = -1;
WITH TIME_TABLE AS(
SELECT (@HOUR := @HOUR +1) AS HOUR
FROM ANIMAL_OUTS
WHERE @HOUR < 23
)

SELECT B.HOUR, COUNT(A.ANIMAL_ID)
FROM TIME_TABLE AS B
LEFT JOIN ANIMAL_OUTS AS A ON B.HOUR = HOUR(A.DATETIME)
GROUP BY B.HOUR
