-- 코드를 입력하세요
WITH BEST AS (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD 
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
    )
    
SELECT U.USER_ID, U.NICKNAME, B.TOTAL_SALES AS TOTAL_SALES 
FROM USED_GOODS_USER AS U
INNER JOIN BEST AS B
ON B.WRITER_ID = U.USER_ID
ORDER BY B.TOTAL_SALES ASC