-- 코드를 작성해주세요
WITH MAXV AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_VALUE
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, (V.MAX_VALUE - E.SIZE_OF_COLONY) AS YEAR_DEV ,E.ID
FROM ECOLI_DATA AS E
INNER JOIN MAXV AS V ON V.YEAR = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY YEAR ASC, YEAR_DEV ASC
