-- 코드를 입력하세요
SELECT FP.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT AS FP
INNER JOIN (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
 FROM FOOD_PRODUCT
WHERE CATEGORY IN ( '과자', '국', '김치', '식용유')
GROUP BY CATEGORY) AS FPO
ON FP.CATEGORY = FPO.CATEGORY AND FP.PRICE = FPO.MAX_PRICE
ORDER BY FP.PRICE DESC